/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/menus/setupMenu copy.vue')['default']
    DailyInspection: typeof import('./src/components/inspection/dailyInspection.vue')['default']
    EditRole: typeof import('./src/components/forms/editRole.vue')['default']
    EditUser: typeof import('./src/components/forms/editUser.vue')['default']
    FeatureMenu: typeof import('./src/components/menus/featureMenu.vue')['default']
    HeaderSetup: typeof import('./src/components/tabs/headerSetup.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/forms/loginForm.vue')['default']
    New: typeof import('./src/components/inspection/new.vue')['default']
    NewHeader: typeof import('./src/components/forms/newHeader.vue')['default']
    NewInsItem: typeof import('./src/components/forms/newInsItem.vue')['default']
    NewInstItem: typeof import('./src/components/forms/newInstItem.vue')['default']
    NewMethod: typeof import('./src/components/forms/newMethod.vue')['default']
    NewMethod_backup: typeof import('./src/components/forms/newMethod_backup.vue')['default']
    NewRank: typeof import('./src/components/forms/newRank.vue')['default']
    NewRole: typeof import('./src/components/forms/newRole.vue')['default']
    NewTool: typeof import('./src/components/forms/newTool.vue')['default']
    NewType: typeof import('./src/components/forms/newType.vue')['default']
    NewUser: typeof import('./src/components/forms/newUser.vue')['default']
    PdfViewer: typeof import('./src/components/inspection/pdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupMenu: typeof import('./src/components/menus/setupMenu.vue')['default']
    Spvcheck: typeof import('./src/components/inspection/spvcheckComp.vue')['default']
    SpvcheckComp: typeof import('./src/components/inspection/spvcheckComp.vue')['default']
    ToolList: typeof import('./src/components/tabs/toolList.vue')['default']
    ToolLIst: typeof import('./src/components/tabs/toolList.vue')['default']
    ToolRank: typeof import('./src/components/tabs/toolRank.vue')['default']
    ToolType: typeof import('./src/components/tabs/toolType.vue')['default']
    TypeSetup: typeof import('./src/components/tabs/typeSetup.vue')['default']
  }
}
