/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/features/leadercheck': RouteRecordInfo<'/features/leadercheck', '/features/leadercheck', Record<never, never>, Record<never, never>>,
    '/features/operatorInspection': RouteRecordInfo<'/features/operatorInspection', '/features/operatorInspection', Record<never, never>, Record<never, never>>,
    '/features/spvcheck': RouteRecordInfo<'/features/spvcheck', '/features/spvcheck', Record<never, never>, Record<never, never>>,
    '/setup/role': RouteRecordInfo<'/setup/role', '/setup/role', Record<never, never>, Record<never, never>>,
    '/setup/tools': RouteRecordInfo<'/setup/tools', '/setup/tools', Record<never, never>, Record<never, never>>,
    '/setup/user': RouteRecordInfo<'/setup/user', '/setup/user', Record<never, never>, Record<never, never>>,
  }
}
